services:
  db:
    image: mysql:8.2.0
    volumes:
      - dbase:/var/lib/mysql
    ports:
      - "3312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: sistema-voto-db-1


volumes:
  dbase:
